### ISSUE TITLE
kubectl dependency on KubeVirt installation on an existing cluster 

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt-ansible#100]
After successful installation of OpenShift cluster (3.7), following [Readme](https://github.com/kubevirt/kubevirt-ansible#openshift-cluster-1), I run into

```
>> ansible-playbook -i localhost playbooks/kubevirt.yml
<...>

TASK [kubevirt : Create kube-system namespace] *********************************************************
Wednesday 28 February 2018  09:57:19 +0100 (0:00:00.254)       0:00:00.361 **** 
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}.
Found: ns.stdout != "{{ namespace }}"

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "kubectl create namespace kube-system",
    "delta": "0:00:00.001448",
    "end": "2018-02-28 09:57:19.575954",
    "rc": 127,
    "start": "2018-02-28 09:57:19.574506"
}

STDERR:

/bin/sh: kubectl: command not found


MSG:

non-zero return code

```

Should I have `kubectl` installed? If so, it should be documented. But the best is to include it in the playbook. After installing `origin-clients` by `dnf` the playbooks proceeds normally.

**Comment by gbenhaim** [comment]
Installing it a part of the playbook will require running with sudo.
We can add a test the check if `kubectl` exists, if not fail the playbook with an informative message.

**Comment by alexxa** [comment]
Whatever way it will be solved, a `kubectl` requirement note in docs should be there and will be appreciated.

**Comment by lukas-bednar** [comment]
@alexxa could you please cover this gap in documentation ?

**Comment by rthallisey** [comment]
> Whatever way it will be solved, a kubectl requirement note in docs should be there and will be appreciated.
>
Definitely should be added to the docs.

**Comment by alexxa** [comment]
@lukas-bednar That was a plan, but @rthallisey beat me.
