### ISSUE TITLE
Failure to log in to the server on playbooks/kubevirt.yml

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt-ansible#101]
playbooks/kubevirt.yml returns login failure.

```  

>> ansible-playbook -i localhost playbooks/kubevirt.yml
<...>
TASK [kubevirt : Create kube-system namespace] *********************************************************
Wednesday 28 February 2018  10:09:05 +0100 (0:00:00.345)       0:00:00.453 **** 
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}.
Found: ns.stdout != "{{ namespace }}"

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "kubectl create namespace kube-system",
    "delta": "0:00:00.097699",
    "end": "2018-02-28 10:09:05.327740",
    "rc": 1,
    "start": "2018-02-28 10:09:05.230041"
}

STDERR:

error: You must be logged in to the server (Unauthorized)

```

**Comment by gbenhaim** [comment]
You should login to the cluster by yourself or specify the following variables:

```
admin_user (a user with cluster-admin permissions)                                                                                                    
admin_password
```

**Comment by alexxa** [comment]
@gbenhaim There is nth like that in docs, in our Readme, and if it's that way, then our docs should be very clear on that, agree?

**Comment by gbenhaim** [comment]
@rthallisey Should it be added to the docs of kubvirt's role?

**Comment by alexxa** [comment]
I think, it should be right before a command which triggers playbooks/kubevirt.yml
```
Before running KubeViert deployment, ensure you are logged in your OpenShift cluster as a user with cluster-admin permissions.

$ oc login <master_fqdn>:<port>
Username:
Password:


```

BTW, using ansible-playbook and providing user/pwd as extra variables disclosures cluster login credentials. One can see them if they list process (`ps -aux | grep ansible-playbook`) or get access to `history`. What do you think about it?

**Comment by rthallisey** [comment]
If you run ```ansible-playbook -i localhost playbooks/kubevirt.yml``` the expectation is you are logged into the cluster.  We'll need to mention this is the docs.

**Comment by alexxa** [comment]
@gbenhaim @rthallisey @lukas-bednar And what do you think about login credentials disclosure I mentioned in my previous comment?
