### ISSUE TITLE
link for docker-storage-setup-defaults is broken

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#110]
it is `https://github.com/kubevirt/kubevirt-ansible/blob/master/docker-storage-setup-defaults`, I think it should link to `https://github.com/openshift/openshift-ansible-contrib/blob/master/roles/docker-storage-setup/defaults/main.yaml`

**Comment by lukas-bednar** [comment]
yes link is wrong in readme.
there is `[defaults values](docker-storage-setup-defaults)` it should be `[defaults values][docker-storage-setup-defaults]` because this link is defined on bottom of readme.

I know that @alexxa already hit same issue.
