### ISSUE TITLE
Document how to run mock environment locally

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#112]
In the CI, the entire automation runs inside a mock environment http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Using_mock_runner/index.html

We should document how to use in order to run the automation locally on a laptop.

**Comment by lukas-bednar** [comment]
Sorry I just opened issue #113 I am closing it ... :smile:

**Comment by alexxa** [comment]
Great minds think alike =)

**Comment by nellyc** [comment]
@gbenhaim whats the status?

**Comment by gbenhaim** [comment]
Fixed https://github.com/kubevirt/kubevirt-ansible/blob/master/automation/README.md
