### ISSUE TITLE
Add an extra 50G disk to each lago VM

### ISSUE THREAD

**Issue by aglitke** [kubevirt/kubevirt-ansible#126]
In order to support a CNS deployment, the hosts need to have an extra, unused disk that can be given to gluster.  Can we update the automation such that vms will be created with this added disk?  The exact size is negotiable but I'd rather have too much (since it is thin provisioned) as opposed to seeing random failures when we run out of space.

**Comment by lukas-bednar** [comment]
@aglitke do you need to initialize that disk somehow ? format it with some fs or something?

**Comment by aglitke** [comment]
Nope.  It should be completely blank.
