### ISSUE TITLE
vars duplication

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt-ansible#146]
[playbooks/cluster/openshift/config.yml#L4](https://github.com/kubevirt/kubevirt-ansible/blob/6b9a4303e7b69a85437e1cf67ca5e26325e20276/playbooks/cluster/openshift/config.yml#L4) duplicates variables from [vars/all.yml](https://github.com/kubevirt/kubevirt-ansible/blob/master/vars/all.yml)

**Comment by alexxa** [comment]
Also, [playbooks/cluster-login.yml](https://github.com/kubevirt/kubevirt-ansible/blob/481d36a0308cf7f84255293d763c346dde67f0e8/playbooks/cluster-login.yml) duplicates variables from [roles/cluster-login/defaults/main.yml](https://github.com/kubevirt/kubevirt-ansible/blob/6b9a4303e7b69a85437e1cf67ca5e26325e20276/roles/cluster-login/defaults/main.yml)

**Comment by alexxa** [comment]
I believe a variable `openshift_playbook_path` is redundant in [playbooks/cluster/openshift/README.md](.playbooks/cluster/openshift/README.md). It's not an independent variable and defined by `openshift_version` in [vars/all.yml](https://github.com/kubevirt/kubevirt-ansible/blob/master/vars/all.yml).

**Comment by nellyc** [comment]
@rthallisey any updates?

**Comment by rthallisey** [comment]
This is some tech debt that I'll come back to when I have time.  There are a few other issues that are higher priority right now.  Going to unassign myself in case someone wants to take this for now.
