### ISSUE TITLE
default openshift to 3.9

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt-ansible#147]
- main readme.md says pull 3.7 openshift branch
- playbooks/cluster/openshift/README.md defaults to 3.7
- kubevirt-ansible/automation/check-patch.sh runs it for 3.7
- kubevirt-ansible/playbooks/cluster/openshift/config.ym defaults it to 3.7 (though it should use vars/all.yml - see issue #146)

But vars/all.yml defaults it to 3.9. We should pick one version, and actually default it to 3.9 since it's the latest release and that's where devs will want to target.

**Comment by lukas-bednar** [comment]
Update openshift-ansible to use released branch of 3.9
