### ISSUE TITLE
kubernetes-deploy playbook doesn't count with multiple masters

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#15]
https://github.com/kubevirt-incubator/kubevirt-ansible/blob/fce05169e39099c4438820aca27c6c300afc0ba0/kubernetes/roles/master/templates/deploy_kubernetes.j2#L21

it will always work with fist host in the group.

**Comment by dcritch** [comment]
So we want that line to run against all masters, not just master[0]?

**Comment by lukas-bednar** [comment]
The line reads `# add to master possibility to schedule pods` So I guess that if we have more masters we probably want to all of them be schedulable ... I am not sure.

**Comment by dcritch** [comment]
Submitted PR293 to address this

**Comment by dcritch** [comment]
This can be closed via PR#293

**Comment by lukas-bednar** [comment]
Thanks
