### ISSUE TITLE
kubevirt-ansible should handle situations such as re-execute playbook after interruption/failure

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#158]
Hi there,

I attempted to install storage_demo using kubevirt-ansible playbook based on [ceph-cinder-demo](https://github.com/rmohr/ceph-cinder-demo). If playbook execution failed or interrupted, I ran playbook again, it can't go ahead once ran into existing resources. I think as long as playbook runs fail, re-run it is inevitable for users. It's an unpractical and annoying experience to delete existent resources when meet one each time. So from development side, all existent resources should be considered and cleaned up or skipped if necessary. 

Here is what I found：
```
# ansible-playbook -i inventory playbooks/storage.yaml -v

fatal: [192.168.121.55]: FAILED! => {
    "changed": true, 
    "cmd": "kubectl create clusterrolebinding c-golden-images-default --clusterrole=cluster-admin --serviceaccount=golden-images:default", 
    "delta": "0:00:00.196894", 
    "end": "2018-03-23 10:18:11.008981", 
    "rc": 1, 
    "start": "2018-03-23 10:18:10.812087"
}

STDERR:

Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "c-golden-images-default" already exists
```

**Comment by lukas-bednar** [comment]
@aglitke do you think that somebody from storage team could cover this issue ?

**Comment by dcritch** [comment]
Hi @qwang1 

I've opened up a PR to fix your issue: https://github.com/kubevirt/kubevirt-ansible/pull/172

**Comment by qwang1** [comment]
@dcritch Thank you!

**Comment by alexxa** [comment]
@dcritch PR #172 fixes things for one role only. Are all other roles are ok to rerun on fail?

**Comment by alexxa** [comment]
@dcritch can you please check whether other roles need to be updated accordingly?

**Comment by alexxa** [comment]
@dcritch David, thanks. Please accept the invite to KuveVirt GitOrg, it should be in your email.

**Comment by dcritch** [comment]
I ran the major top level playbooks ( {cdi,cluster-login,kubevirt,selinux,storage}.yml ) and didn't notice any idempotency issues. 

Looking over things though, there are definitely some spots where we can fix things up. There are a lot of uses of command and shell, where a proper ansible module is available. There is a trello card for it, but I can take on that issue of clean up. I think this one can be closed.

**Comment by alexxa** [comment]
Thank you, @dcritch
