### ISSUE TITLE
Optmize storage_demo ansible role

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#159]
Hi there,

I attempted to install storage_demo using kubevirt-ansible playbook based on [ceph-cinder-demo](https://github.com/rmohr/ceph-cinder-demo). Perhaps my testing environment is new and nothing configured, so I ran into some problems. I think the following modification would be better if deploy it on multi-node clusters, just for reference. 

```
# cat kubevirt-ansible/playbooks/storage.yml
- hosts: localhost ---> masters[0]
connection: local ---> comment it # connection: local

# cat kubevirt-ansible/inventory
[OSEv3:vars]
add ---> ansible_ssh_private_key_file="~/.ssh/keyname"

# BEGIN CUSTOM SETTINGS
[etcd] --> Since there is not an etcd under [OSEv3:children], comment it ---> #[etcd]
```

**Comment by lukas-bednar** [comment]
@aglitke could you please share, what do you think about suggested change to `playbooks/storage.yml` ?

**Comment by dcritch** [comment]
I agree on point #1 and for #3, really etcd should be in the children anyway, so I've submitted a PR to address those 2 things.

For #2, its reasonable to assume folks are using their default SSH key under ~/.ssh/... If this doesn't work for a given environment, the key can be specified on the command line via:
# ansible-playbook --private-key path/to/key ....

**Comment by qwang1** [comment]
@dcritch Thanks. The modification haven't caused regression issue yet.
