### ISSUE TITLE
deploy Linux&Windows default templates

### ISSUE THREAD

**Issue by michalskrivanek** [kubevirt/kubevirt-ansible#182]
It would be nice if we include the basic examples of Windows and Linux Templates out of the box. They will show up nicely in Console when you want to create a VM in GUI

**Comment by michalskrivanek** [comment]
@rthallisey can you think of best place where to do that?

**Comment by fabiand** [comment]
Side note - We've got two templates in the KubeVirt repo which can be used:

https://github.com/kubevirt/kubevirt/blob/master/cluster/vm-template-windows2012r2.yaml
https://github.com/kubevirt/kubevirt/blob/master/cluster/vm-template-rhel7.yaml

We'll just need to sort out who will deploy the required presets. Ansible or core kubevirt. I tend to let it be core kubevirt.

/cc @rmohr

**Comment by karmab** [comment]
both templates would need the extra tag *virtualmachine* in order to show up in the virtualization category

**Comment by rmohr** [comment]
@fabiand sounds good to me, for as long as we can rethink this as soon as the api is more stable.

**Comment by rthallisey** [comment]
@michalskrivanek Already adding the kubevirt [default](https://github.com/kubevirt/kubevirt/blob/master/cluster/vm-template-fedora.yaml) templates [here](https://github.com/kubevirt/kubevirt-ansible/blob/master/roles/kubevirt/tasks/provision.yml#L67-L71)

**Comment by rmohr** [comment]
Hm, ok. Note that we move everything in the git repo around without notice. So you can easily run into issues if you reference something in our repo which is not downloaded from a release ...

**Comment by fabiand** [comment]
@rthallisey currently it would, because the templates are not on the release page: https://github.com/kubevirt/kubevirt/releases/tag/v0.4.1-alpha.1

What does work is to pull the templates from the tag tree: https://github.com/kubevirt/kubevirt/tree/v0.4.1-alpha.1

**Comment by rthallisey** [comment]
@fabiand I pull down the released tar ball -> https://github.com/kubevirt/kubevirt/archive/v0.4.1-alpha.1.tar.gz , untar, and grab the templates.

It would be nice to have the templates on the release page or in any published location with tag.  We could do something like a container that gets run by a kubernetes job and does a few ```oc create -f xxxxx```.

**Comment by fabiand** [comment]
@rthallisey ah, tarball works!

For now we will not put the templates on the release page, as they are depending on OpenShift functionality. Once we have a way to provide the tempaltes to vanilla Kubernetes users, then I think that we can place them on the release page.

But if you need a link, then the tag tree link should work for kubectl as well.

**Comment by michalskrivanek** [comment]
@rthallisey , is this only missing the relist? We do not necessarily need custom templates right now

**Comment by rthallisey** [comment]
We need to make sure these templates are annotated properly for the TSB to pick them up.  Then we'll need a relist of the TSB in the playbooks.

Before we do that,  we're still seeing an [issue](https://github.com/openshift/origin/issues/19368) in the TSB when running CRDs.

**Comment by fabiand** [comment]
@rthallisey can you ellaborate why you need to define CRDs using a template?

**Comment by rthallisey** [comment]
I'm mentioning the wrong resource, it's the OfflineVirtualMachine API endpoint.  This is an apiserver extension that isn't currently allowed by the TSB.
