### ISSUE TITLE
[enhancement] allow for remote execution of "oc" during install

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt-ansible#188]
Currently [this](https://github.com/kubevirt/kubevirt-ansible/tree/master/playbooks#install-kubevirt-on-an-existing-cluster) section requires either ```oc``` to be installed on the machine that does the installation, or to do the installation from the master node.
The drawback with first option that the ```.kube/config``` has to be copied from the master to the installing machine, the drawback with the second option is that the master is used for installation, and would need git, and ansible to be installed on it. This is fine when the cluster is used by a developed (as this is already needed for using APBs in openshift), but does not make sense when the cluster is used for other purposes.
Ideally, ```oc``` is remotely executed by ansible.

**Comment by rthallisey** [comment]
Looks like the kubevirt playbooks uses localhost.  I think we'll need to change it to master[0] like in storage.

**Comment by yuvalif** [comment]
@dcritch is it safe to close the issue? was it addressed by PR #282 ?

**Comment by dcritch** [comment]
@yuvalif Yup, this can be closed
