### ISSUE TITLE
Optimize cdi playbook

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#195]
Hi there,
Considering situations like HA cluster, multi-node cluster, and ansible host is not one master, so I think the following modification would be better. These change can provision/deprovision CDI successfully on my cluster as well.
```
# cat kubevirt-ansible/playbooks/cdi.yml
- hosts: localhost ---> masters[0]
connection: local ---> comment it # connection: local
```

**Comment by dcritch** [comment]
This will be fixed with PR [193](https://github.com/kubevirt/kubevirt-ansible/pull/193/)
