### ISSUE TITLE
Missing required field "apiGroup" and "kind" in io.k8s.api.rbac.v1.RoleRef

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#211]
Hi there,

I tried to provision storage-glusterfs with external_provisioner enabled. I met this problem when kubevirt-ansible executed "Create storage-glusterfs Resources":
error: error validating "/tmp/storage-glusterfs.yml": error validating data: [ValidationError(ClusterRoleBinding.roleRef): missing required field "apiGroup" in io.k8s.api.rbac.v1.RoleRef, ValidationError(ClusterRoleBinding.roleRef): missing required field "kind" in io.k8s.api.rbac.v1.RoleRef]; if you choose to ignore these errors, turn validation off with --validate=false

Here is part of ansible log:
```
[root@dhcp-140-90 kubevirt-ansible]# ansible-playbook --private-key /home/qwang/libra-new.pem -i inventory_glusterfs -e action=provision -e glusterfs_namespace=glusterfs -e storage_role=storage-glusterfs -e external_provisioner=true playbooks/storage.yml -v
<------------------------snip------------------------->
TASK [storage-glusterfs : Render storage-glusterfs deployment yaml] ***********************************************************
Thursday 26 April 2018  16:32:02 +0800 (0:00:00.055)       0:01:15.036 ******** 
changed: [host-8-249-87.host.centralci.eng.rdu2.redhat.com] => {
    "changed": true, 
    "checksum": "2e38d8da8badf2f8014e20237978dfcdfcc84ca6", 
    "dest": "/tmp/storage-glusterfs.yml", 
    "gid": 0, 
    "group": "root", 
    "md5sum": "ef48e1e016b7b5d8134a2090a961ff00", 
    "mode": "0644", 
    "owner": "root", 
    "secontext": "unconfined_u:object_r:admin_home_t:s0", 
    "size": 2653, 
    "src": "/root/.ansible/tmp/ansible-tmp-1524731522.64-133305358774337/source", 
    "state": "file", 
    "uid": 0
}

TASK [storage-glusterfs : Create storage-glusterfs Resources] *****************************************************************
Thursday 26 April 2018  16:32:53 +0800 (0:00:51.027)       0:02:06.064 ******** 
fatal: [host-8-249-87.host.centralci.eng.rdu2.redhat.com]: FAILED! => {
    "changed": true, 
    "cmd": [
        "kubectl", 
        "apply", 
        "-n", 
        "glusterfs", 
        "-f", 
        "/tmp/storage-glusterfs.yml"
    ], 
    "delta": "0:00:00.443498", 
    "end": "2018-04-26 04:33:17.793660", 
    "rc": 1, 
    "start": "2018-04-26 04:33:17.350162"
}

STDOUT:

secret "kubevirt-heketi-secret" created
storageclass "kubevirt" created
clusterrole "glusterfile-provisioner-runner" created
serviceaccount "glusterfile-provisioner" created


STDERR:

error: error validating "/tmp/storage-glusterfs.yml": error validating data: [ValidationError(ClusterRoleBinding.roleRef): missing required field "apiGroup" in io.k8s.api.rbac.v1.RoleRef, ValidationError(ClusterRoleBinding.roleRef): missing required field "kind" in io.k8s.api.rbac.v1.RoleRef]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by nellyc** [comment]
@qwang1 is this still relevant? storageclasses were removed.
can we close it?

**Comment by qwang1** [comment]
@nellyc 
I'd like to clarify these questions before giving an answer:
Q1. For now StorageClass were removed from import-vm-apb https://github.com/ansibleplaybookbundle/import-vm-apb/pull/29 , will it be removed from kubevirt-apb or other APB(if have) as well?
Q2. Storage and kubevirt has been decoupled and can't show on web console. We won't keep them deploying together through kubevirt-ansible on CLI anymore?
Q3. Will external_provisioner be supported? I thinks so because I saw some code addition for it. This issue happens as long as external_provisioner enabled.
If Q1, Q2 are yes, I think this is not relevant and can be close.

**Comment by nellyc** [comment]
@qwang1 
Q1: Yes, the APBs will be storage agnostic. i believe it was already removed from kubevirt-ansible, and should reflect in the APB
Q2: If you are asking about decoupling kubevirt & CDI installation, thats incorrect, CDI is still installed as part of the kubevirt installation, it just doesnt 'care' about the storage backend which is being used, it takes the default
Q3: AFAIK yes

**Comment by qwang1** [comment]
Do not need to test the storage roles anymore, so close it.
