### ISSUE TITLE
move task "Configure oc admin user for testing" to role kubevirt?

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#233]
The task is currently in `playbooks/cluster/openshift/config.yml`, if I deployed a cluster not via kubevirt-ansible, I still want `test_admin` is configured for testing. 

How about move it to role kubevirt?

**Comment by lukas-bednar** [comment]
I think the best would be move this task out of `playbooks/cluster/openshift/config.yml`, and make it either  role, or separate playbook which could be included on relevant places.

I already was thinking about this move some time ago when trying deploying kubevirt on existing cluster.

So from me thumb up on this one.
