### ISSUE TITLE
no storage components installed when using glusterfs role

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt-ansible#234]
no storage components gets installed when using glusterfs role ( from the kubevirt-apb)
- expected to see the playbooks/cdi.yml executed and the cdi components installed ( and kubevirt storage class created) but only kubevirt got deployed
- worth mentioning i used 0.5.0 version for kubevirt

opening the issue here as the apb leverages the code from this repository

**Comment by simon3z** [comment]
cc @aglitke

**Comment by nellyc** [comment]
@aglitke ping

**Comment by aglitke** [comment]
Fixed by #288
