### ISSUE TITLE
why we disable storage tests in CI ?

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt-ansible#252]
The storage-demo role was introduced in here: https://github.com/kubevirt/kubevirt-ansible/pull/120,
and after that seems we disabled it in CI in this pr https://github.com/kubevirt/kubevirt-ansible/pull/139, is there any reason we disable it by default ? 
I'm currently working on CDI stroage e2e test, if we disabled it, I won't able to check the pvc binded success and importer-pod being completed in CI.

@rthallisey @lukas-bednar @aglitke

**Comment by shiywang** [comment]
Okay, I check the pr here: https://github.com/kubevirt/kubevirt-ansible/pull/189, maybe we intended to add gluster storage as default ci testing, but is that pr working currently ? for 3.7 or 3.10 ? 
@jarrpa

**Comment by lukas-bednar** [comment]
@shiywang Gal is working on enabling cns on CI for ocp-3.10 in pr #241.
