### ISSUE TITLE
it's still v0.4.1 after deployed kubevirt

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#259]
PR #230 has updated the version to `0.5.0` in `vars/all.yml`, but it's still `0.4.1` after deployed kubevirt. It should be caused by the version in `roles/kubevirt/defaults/main.yml` overwrite the version in `vars/all.yml`. Should we have this variable in both place or just keep one in `vars/all.yml`.

**Comment by lukas-bednar** [comment]
@gouyang thanks for report!
