### ISSUE TITLE
StorageClass fails to work on single-node Gluster environment

### ISSUE THREAD

**Issue by nixpanic** [kubevirt/kubevirt-ansible#260]
There is [`volumeoptions: "group virt"`](https://github.com/kubevirt/kubevirt-ansible/blob/master/roles/storage-glusterfs/templates/storage-glusterfs.yml.j2#L29) which will fail to apply for non-replicated volumes. This will cause failure on creating PVs through this StorageClass.

On single-node deployments, we probably should enable a subset of the `group virt` options. The options are listed in the [`group-virt.example` file](https://github.com/gluster/glusterfs/blob/master/extras/group-virt.example) in the glusterfs repository.

Is there a way to detect if the deployment of kubevirt (or ideally Gluster) is on a single node?

**Comment by KritikaDhananjay** [comment]
group-virt for non-replicate volumes (after dropping the AFR options):

performance.quick-read=off
performance.read-ahead=off
performance.io-cache=off
performance.low-prio-threads=32
network.remote-dio=enable
cluster.server-quorum-type=server
features.shard=on
user.cifs=off

**Comment by jarrpa** [comment]
Just to chime in: I can't think of a way to detect single-node mode off-hand. The deployment would just have to choose one set of options or the other based on knowing the user input for either single- or multi-node deployments.

**Comment by nixpanic** [comment]
/remove-lifecycle stale

This is still something we want to address. However optimizations for a single-node Gluster environment are not a priority item at the moment.
