### ISSUE TITLE
stroage-demo: hard-coded target node could choose master

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt-ansible#270]
currently storage-demo select nodes just hard-coded item[0] [here](https://github.com/kubevirt/kubevirt-ansible/blob/master/roles/storage-demo/tasks/provision.yml#L30) this is not right when this situation happened:

```
[root@qe-testwang-testmaster-etcd-nfs-1 ~]# oc get nodes
NAME                                     STATUS    ROLES     AGE       VERSION
qe-testwang-testmaster-etcd-nfs-1        Ready     master    22m       v1.9.1+a0ce1bc657
qe-testwang-testnode-registry-router-1   Ready     compute   22m       v1.9.1+a0ce1bc657
```

**Comment by sreichar** [comment]
storage roles are being removed from kubevirt-ansilble and kubevirt-apb

**Comment by sreichar** [comment]
https://github.com/kubevirt/kubevirt-ansible/pull/264
