### ISSUE TITLE
CDI: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: 

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt-ansible#284]
```
[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ oc logs -f cdi-deployment-775d5bb9bd-zf8jn
W0613 07:59:50.132669       1 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0613 07:59:50.134640       1 datavolume-controller.go:100] Setting up event handlers
I0613 07:59:50.135374       1 datavolume-controller.go:138] Starting DataVolume controller
I0613 07:59:50.135385       1 datavolume-controller.go:141] Waiting for informer caches to sync
E0613 07:59:50.157872       1 reflector.go:205] github.com/kubevirt/containerized-data-importer/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: User "system:serviceaccount:golden-images:cdi-sa" cannot list datavolumes.cdi.io at the cluster scope: User "system:serviceaccount:golden-images:cdi-sa" cannot list all datavolumes.cdi.io in the cluster
E0613 07:59:51.159729       1 reflector.go:205] github.com/kubevirt/containerized-data-importer/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: User "system:serviceaccount:golden-images:cdi-sa" cannot list datavolumes.cdi.io at the cluster scope: User "system:serviceaccount:golden-images:cdi-sa" cannot list all datavolumes.cdi.io in the cluster
E0613 07:59:52.161204       1 reflector.go:205] github.com/kubevirt/containerized-data-importer/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: User "system:serviceaccount:golden-images:cdi-sa" cannot list datavolumes.cdi.io at the cluster scope: User "system:serviceaccount:golden-images:cdi-sa" cannot list all datavolumes.cdi.io in the cluster
E0613 07:59:53.162840       1 reflector.go:205] github.com/kubevirt/containerized-data-importer/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: User "system:serviceaccount:golden-images:cdi-sa" cannot list datavolumes.cdi.io at the cluster scope: User "system:serviceaccount:golden-images:cdi-sa" cannot list all datavolumes.cdi.io in the cluster
E0613 07:59:54.164853       1 reflector.go:205] github.com/kubevirt/containerized-data-importer/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.DataVolume: datavolumes.cdi.io is forbidden: User "system:serviceaccount:golden-images:cdi-sa" cannot list datavolumes.cdi.io at the cluster scope: User "system:serviceaccount:golden-images:cdi-sa" cannot list all datavolumes.cdi.io in the cluster
```

with kubevirt change to v0.6.0 seems there's a new resources added but we don't add it in cdi ClusterRole, I'm worried about this tighten cdi roles will make code constantly change when new resource being added, and sometimes we forgot to add it then it won't works.

@copejon @jeffvance
@gbenhaim @fabiand @rmohr

**Comment by shiywang** [comment]
Okay, I check the latest code, there's some change here, and issue https://github.com/kubevirt/containerized-data-importer/issues/192 to track this, but our kubevirt-ansible already update to v0.6.0, but cdi seems haven't synced up with it.

**Comment by gbenhaim** [comment]
What do we need to do in order to catch this kind of errors in CI?

**Comment by davidvossel** [comment]
hey, 

So there's a few problems going on here. I'll describe what I see.

1. CDI's release appears to be getting overwritten with every commit at the moment. This means for example that someone using the CDI v0.5.2 will get different code each time they they deploy depending on what happend upstream

So, we have to make CDI releases immutable. 

2. Kubevirt-ansible isn't pulling manifests from CDI releases, instead there is a manifest template being used. see **roles/cdi/templates/cdi-controller-deployment.yml**.

This presents the same problem's that we have with KubeVirt. Just like the KubeVirt manifest changes between releases, CDI will do the same.  The upstream CDI controller manifest has the 'list' permissions for the DataVolume object, but the kubevirt-ansible version does not.

**Comment by jeffvance** [comment]
Related: [cdi issue 203](https://github.com/kubevirt/containerized-data-importer/issues/203)

**Comment by shiywang** [comment]
> What do we need to do in order to catch this kind of errors in CI?

Enable glusterfs and once my pr https://github.com/kubevirt/kubevirt-ansible/pull/246 merged, I think we should be able to catch this kind of errors.

**Comment by shiywang** [comment]
> Kubevirt-ansible isn't pulling manifests from CDI releases, instead there is a manifest template being used. see roles/cdi/templates/cdi-controller-deployment.yml.
This presents the same problem's that we have with KubeVirt. Just like the KubeVirt manifest changes between releases, CDI will do the same. The upstream CDI controller manifest has the 'list' permissions for the DataVolume object, but the kubevirt-ansible version does not.

This is what me and @lukas-bednar have to update the manifests every time, I would say so far manually update is still acceptable, but the more intelligence way is automate it, at least we have a mechanism to make sure it won't mess up and keep in sync.

I'm thinking about for kubevirt-ansible, it's like the integration test repo for all the components: kubevirt, cdi... could we introduce a staging dir like kubernetes [here](https://github.com/kubernetes/kubernetes/tree/0f5f4597e06cbc3e300f5ab0f41e0acf52c34d58/staging) to make sure kubevirt-ansible to fetch desired version manifests code we want ?

@nellyc @lukas-bednar @jeffvance @davidvossel 
I don't know if it's a feasible plan, but I would like to research on it.
