### ISSUE TITLE
KubeVirt deprovision doesn't count with offline templates

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#322]
When taking look at `roles/kubevirt/tasks/deprovision.yml` I see that it doesn't check if offline templates are available.

@rthallisey is this intentional ?

**Comment by lukas-bednar** [comment]
I also noticed that deprovisioning doesn't remove VM templates. Is it ok ?

**Comment by lukas-bednar** [comment]
> It's ok if the vm aren't removed, 

I mean VM Templates, these which are installed by provision.yml playbook.

**Comment by nellyc** [comment]
@rthallisey any updates on this one?
