### ISSUE TITLE
Need to specify IMPORTER_IMAGE in controller manifest jinja

### ISSUE THREAD

**Issue by sreichar** [kubevirt/kubevirt-ansible#327]
When IMPORTER_IMAGE is not set, the controller will launch importer using docker.io/kubevirt/cdi-importer

Believe we need to modify kubevirt-ansible/roles/cdi/templates/cdi-controller-deployment.yml
to have a env variable name IMPORTER_IMAGE set to {{ repo_tag }}/virt-cdi-importer:{{ release_tag }}

**Comment by shiywang** [comment]
I'm working on it

**Comment by shiywang** [comment]
it was fixed, I think we can close
