### ISSUE TITLE
test function ProcessTemplateWithParameters isn't flexible

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#336]
The problems I can think of:
1. It does not work with template from openshift namespace, like ` oc process -n openshift fedora-vm-template  -p NAME=fedora`
2. It's hard coding "-p", cannot handle `oc process -n openshift fedora-vm-template  -p NAME=fedora -p CPU=2 -p MEMORY=2048`

It can be simplified as `func ProcessTemplateWithParameters(dstFilePath string, params ...string) string`

@shiywang

**Comment by shiywang** [comment]
thanks for the suggestion!! for 1,2. it looks like the same issue for me, so I will add namespace into this function and make it more flexible in a follow-up pr. For parameter I can add an exposed function only deal with the template fetch from openshift namespace.
