### ISSUE TITLE
Add flag kubectl-path for tests in hack/run-tests.sh

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#349]
Details in http://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1077//artifact/check-patch.openshift_3-10.el7.x86_64/mock_logs/script/stdout_stderr.log.

The tests is failed at below lines, the root cause is it cannot find kubectl binary, add `-kubectl-path=/usr/bin/kubectl` should fix it.

```
/root/go/src/kubevirt.io/kubevirt-ansible/tests/node_eviction_test.go:94
/root/go/src/kubevirt.io/kubevirt-ansible/tests/node_eviction_test.go:147
```

And it surprise me that it's not happened to oc.

**Comment by shiywang** [comment]
Yes, because oc has a `lookup` function, but it had already been removed by upstream, so once we upgrade vendor, it will become a problem.

**Comment by gouyang** [comment]
Change the code to use "oc adm drain" now.
