### ISSUE TITLE
should have option to pass custom timeout

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt-ansible#385]
https://github.com/kubevirt/kubevirt-ansible/blob/8d91e5da424729865847d5520f482e2e64754c60/tests/util.go#L147

tests such as v2v #352 might require more then 2m to appear, having a param to pass custom waiting time would be helpful in such cases

**Comment by shiywang** [comment]
yes, we can do that, I'll add it in a folloow up pr

**Comment by shiywang** [comment]
fixed in https://github.com/kubevirt/kubevirt-ansible/pull/384 
@vatsalparekh
