### ISSUE TITLE
Define common environment variables 

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt-ansible#394]
Commonly used details about kubevirt/openshift cluster details should be available as environment variables to be used by tests in CI

**Comment by lukas-bednar** [comment]
As discussed on call with Vatsal, there is a need to manipulate with sensitive data which are not really good to be stored in repository.

I like how ManageIQ project is dealing with this issue - create eyaml (encrypted yaml) with all sensitive content, and export single variable with a Key to decode this file on runtime.

We can do exactly the same here ... if you have other suggestion please share!

**Comment by gbenhaim** [comment]
@vatsalparekh Do you have a specific requirement? What deployment do you need?

**Comment by vatsalparekh** [comment]
@gbenhaim @lukas-bednar I was mainly referring to having details like ocp user/pass, vmware cluster details as env var so tests can consume it. But we can go with yamls as well, my main request was to have them defined common so we can remove hard-coding them in tests.
