### ISSUE TITLE
Failed to deploy Multus from remote machine 

### ISSUE THREAD

**Issue by myakove** [kubevirt/kubevirt-ansible#396]
When trying to deploy Multus from a remote machine (not from the master) we fail with an error:
Tuesday 02 October 2018  17:01:59 +0300 (0:00:00.022)       0:00:00.208 ******* 
Using module file /home/myakove/.local/lib/python2.7/site-packages/ansible/modules/commands/command.py
<172.16.0.16> ESTABLISH LOCAL CONNECTION FOR USER: myakove
<172.16.0.16> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uwkskdvhbnrynigdxyybdhmxzxadboqv; http_proxy='"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' /usr/bin/python'"'"' && sleep 0'
changed: [172.16.0.16] => {
    "changed": true, 
    "cmd": "oc get ns | grep -w kube-system | awk '{ print $1 }'", 
    "delta": "0:00:00.113908", 
    "end": "2018-10-02 17:01:59.392219", 
    "invocation": {
        "module_args": {
            "_raw_params": "oc get ns | grep -w kube-system | awk '{ print $1 }'", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2018-10-02 17:01:59.278311"
}

STDERR:

the server doesn't have a resource type "ns"

TASK [network-multus : Create kube-system namespace] ***********************************************************************************************************************
task path: /home/myakove/go/src/kubevirt.io/kubevirt-ansible/roles/network-multus/tasks/provision.yml:22
Tuesday 02 October 2018  17:01:59 +0300 (0:00:00.351)       0:00:00.559 ******* 
Using module file /home/myakove/.local/lib/python2.7/site-packages/ansible/modules/commands/command.py
<172.16.0.16> ESTABLISH LOCAL CONNECTION FOR USER: myakove
<172.16.0.16> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-cykseygvromsyqsyqxxsokdnyurkgwcu; http_proxy='"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' /usr/bin/python'"'"' && sleep 0'
fatal: [172.16.0.16]: FAILED! => {
    "changed": true, 
    "cmd": "kubectl create namespace kube-system", 
    "delta": "0:00:00.002052", 
    "end": "2018-10-02 17:01:59.522058", 
    "invocation": {
        "module_args": {
            "_raw_params": "kubectl create namespace kube-system", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 127, 
    "start": "2018-10-02 17:01:59.520006"
}

STDERR:

/bin/sh: kubectl: command not found

MSG:

non-zero return code

The command to deploy:
ansible-playbook -i inventory.inv playbooks/network.yml -e 'network_role=network-multus' -e apb_action=provision 

Work as expected only when running from the master.

**Comment by SchSeba** [comment]
@gbenhaim This is unrelated to the network playbook it also append on the kubevirt playbook.

After looking into the logs the problem is that we are running the code as root.
```
<172.16.0.16> ESTABLISH LOCAL CONNECTION FOR USER: myakove
<172.16.0.16> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uwkskdvhbnrynigdxyybdhmxzxadboqv; http_proxy='"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' /usr/bin/python'"'"' && sleep 0'
```
And the root user doesn't have the config file for the cluster communication.
after running `sudo oc login` the ansible playbook works. (also copy the config file will work)

@myakove Thanks for the help!

**Comment by gbenhaim** [comment]
@SchSeba Anything need to be changed in kubevirt-ansible?

**Comment by SchSeba** [comment]
@gbenhaim I dont know if the is intended or maybe need to document it.
Adding @lukas-bednar maybe he can help us.

**Comment by SchSeba** [comment]
@myakove can we can close this issue? 
related to https://github.com/kubevirt/kubevirt-ansible/pull/526
