### ISSUE TITLE
Improve user experience of install-kubevirt-release playbook

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#43]
Right now playbook runs inside of mock as a part of lago environment, I would like to see it to be able to run also outside of mock under regular user.

- [ ] Extend readme with guide how to install KubeVirt release on existing cluster, step by step
- [x] Playbook itself shouldn't require root user to execute playbook
- [ ] Add minimal inventory file with necessary parameters to install KubeVirt release on existing cluster
- [x] `openshift/roles/kubevirt` role requires kubeconfig file, and in addition there are credentials required - I think it should be converged

**Comment by fabiand** [comment]
@lukas-bednar why is the local root user required?

**Comment by lukas-bednar** [comment]
@fabiand playbook is adding master node to `/etc/hosts`.
https://github.com/kubevirt-incubator/kubevirt-ansible/blob/0e5ae43551e1b50e569a303e9ca53e02b5705988/install-kubevirt-release.yml#L31-L35

**Comment by gbenhaim** [comment]
The purpose of `install-kubevirt-release.yml`  is to emulate the tasks that are done for you by the 
APB. 

A couple of notes:
- What do you mean by saying `add minimal inventory file with credentials and master node` ?
- Which part of the playbook makes it tied to lago?
- `openshift/roles/kubevirt` will be the basis for an APB, it shouldn't handle the login process to the cluster, because the APB is doing it for you.

**Comment by lukas-bednar** [comment]
@gbenhaim I changed title & improved description

> What do you mean by saying add minimal inventory file with credentials and master node ?

I meant that the inventory file example, contains many parameters related to OCP / K8S deployment, which are not necessary for installation KubeVirt on running cluster.
I would add inventory file for installation of KubeVirt only with mandatory options only, or it is enough just document them in readme properly.

> Which part of the playbook makes it tied to lago?

I meant outside of mock, as a non-root user - I fixed that.

> openshift/roles/kubevirt will be the basis for an APB, it shouldn't handle the login process to the cluster, because the APB is doing it for you.

That is correct.

**Comment by gbenhaim** [comment]
I think that mandatory options can be specified directly to ` install-kubevirt-release` via `-e`  flag of `ansible-playbook` command.

**Comment by fabiand** [comment]
Could an IP be used instead of a name?

Also - this is primarily relevant for vagrant setup - not for kube in general. In other words: It's only relevant if DNS is not working properly.

**Comment by gbenhaim** [comment]
Last time I have tried, `oc` command expected the cluster's hostname will be resolvable (even when trying to connect using an IP). I can verify it again...

**Comment by fabiand** [comment]
@gbenhaim hm - right - could you also try vagrant-hostmanager (dnf installable)?

We need to drop the root requirements.

**Comment by lukas-bednar** [comment]
Based on discussion with Gal, we came with conclusion that playbook `install-kubevirt-release.yml' is supposed to simulate APB, where it should run inside of APB container.

So we decided that we will add separate playbook for user, that is addressed in #57 .
It solves all aspects of this issue:
* no root user
* added spep by step guide and video how to install it
* dropped inventory file
* it uses only single type of credentials - kubeconfig

So I am closing this issue in favor of #57.
