### ISSUE TITLE
Accelerate CI

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#44]
- [ ] Cache Openshift containers on the Jenkins slaves
- [x] Run test suite in parallel.
- [x] Don't run full system update, update just the required packages.
- [ ] Install only needed deps, for example when running `install-kubevirt-release.yml`, there is no need to install `andrewrothstein.go-dev` from ansible galaxy.
- [x] Add a profiler to Ansible
- [x] Use std-ci yum repos mirrors https://github.com/kubevirt/kubevirt-ansible/issues/82
- [x] Don't run tests if only the docs changed https://github.com/kubevirt/kubevirt-ansible/pull/81

**Comment by nellyc** [comment]
@gbenhaim when do we want to target this? mvp0.1.2 sounds fair?

**Comment by gbenhaim** [comment]
@nellyc  How much time do we have until `mvp0.1.2`?

**Comment by nellyc** [comment]
@gbenhaim approx 2 months

**Comment by gbenhaim** [comment]
We can have it in 2 months.
