### ISSUE TITLE
Installing KubeVirt on upstream Kubernetes is broken

### ISSUE THREAD

**Issue by rwsu** [kubevirt/kubevirt-ansible#458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Ansible playbook fails to install KubeVirt because "oc" command cannot be found.

**What you expected to happen**:
The playbook installs KubeVirt successfully. The playbook should not be executing the "oc" command if the environment/platform is "kubernetes" and not "openshift".

**How to reproduce it (as minimally and precisely as possible)**:
Install upstream Kubernetes cluster using this guide: https://github.com/kubevirt/kubevirt-ansible/blob/master/playbooks/README.md

Then install KubeVirt using:
sudo ansible-playbook playbooks/kubevirt.yml -e@vars/all.yml -e cluster=kubernetes --connection=local -i inventory

When installing KubeVirt on the Kubernetes cluster, ansible will fail in the "Identify cluster" task because oc is not available in upstream Kubernetes:

2018-11-12 23:25:06,517 p=10972 u=root | Gathering Facts --------------------------------------------------------- 0.61s
2018-11-12 23:25:07,569 p=13606 u=root | PLAY [all] *********************************************************************
2018-11-12 23:25:07,579 p=13606 u=root | TASK [Identify cluster] ********************************************************
2018-11-12 23:25:07,579 p=13606 u=root | Monday 12 November 2018 23:25:07 +0000 (0:00:00.064) 0:00:00.064 *******
2018-11-12 23:25:07,831 p=13606 u=root | fatal: [ip-10-0-3-12.ec2.internal]: FAILED! => {
"changed": false,
"cmd": "oc get projects",
"rc": 2
}

MSG:

[Errno 2] No such file or directory

2018-11-12 23:25:07,834 p=13606 u=root | to retry, use: --limit @/home/centos/kubevirt-ansible/playbooks/kubevirt.retry

2018-11-12 23:25:07,834 p=13606 u=root | PLAY RECAP *********************************************************************

**Anything else we need to know?**:

**Environment**:
- kubevirt-ansible version(use git rev-parse HEAD): 25d9620
- KubeVirt version (use virtctl version): 0.9.3
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`):
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by markllama** [comment]
* kubectl and origin-clients RPMs conflict
* kubeadm requires kubectl
* ansible playbook uses oc hard-coded
* ansible playbook requests 'projects' from oc, which does not exist in stock kubernetes

**Comment by booxter** [comment]
There is a WIP branch to fix some of these issues here: https://github.com/booxter/kubevirt-ansible/tree/fix-kubevirt-ansible

**Comment by booxter** [comment]
With the patches included in the forked branch I referenced above, I now experience the following error:

```
 # ansible-playbook -i  inventory playbooks/kubevirt.yml
-e@vars/all.yml -e cluster=kubernetes
...
fatal: [kubdev]: FAILED! => {
    "attempts": 20,
    "changed": true,
    "cmd": "kubectl -n kube-system get daemonset | grep
kube-multus-amd64 | awk '{ if ($3 == $4) print \"0\"; else print
\"1\"}'",
    "delta": "0:00:00.094178",
    "end": "2018-11-29 20:30:20.185225",
    "rc": 0,
    "start": "2018-11-29 20:30:20.091047"
}

STDERR:

The connection to the server 10.35.19.194:6443 was refused - did you
specify the right host or port?
```

This also broke my kubectl access to the cluster. I believe multus deployment may have screwed networking on the cluster somehow.

For the record, the k8s cluster was deployed with:

```
kubeadm init --pod-network-cidr=10.244.0.0/16
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
```
