### ISSUE TITLE
Try to use the test suite from Kubevirt's repo

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#47]

**Comment by fabiand** [comment]
Makes sense.

All functests are compiled into a binary (`tests.test`) this binary can be run against other K8s or Origin instances, kubevirt uses:

```
${TESTS_OUT_DIR}/tests.test -kubeconfig=${kubeconfig} -test.timeout 30m ${FUNC_TEST_ARGS}
```

But you can obviously use a different kubeconfig.

Also, tests.test could also be shipped in a container for convenience.

**Comment by rthallisey** [comment]
Look at Roman's Kubevirt containerized tests

**Comment by gbenhaim** [comment]
@nellyc, Didn't we decide not to go with this option, and have our own tests?

**Comment by nellyc** [comment]
@gbenhaim we need to run all functional tests, so both containerized kubevirt/cdi tests and kubevirt-ansible tests
