### ISSUE TITLE
Can not spawn new containers after removing multus pods

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#477]
When multus is removed, then there are still hanging configuration files on every node.
For example `/etc/cni/net.d/00-multus.conf` .
Presence of this file causes that you can not spawn any new pod after multus removal ...

Note this is clone of https://bugzilla.redhat.com/show_bug.cgi?id=1651693 .

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**: No pod can be spawned after multus removal 

**What you expected to happen**: I can spawn new pod

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubevirt with apb, and then deprovision it. Then try to schedule any new pod ...

**Anything else we need to know?**:

brew2-virtualization-depr-7hltt     bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3                  0/1       ContainerCreating   0          23m

In events I can read:
  Warning  FailedCreatePodSandBox  3m (x79 over 21m)  kubelet, cnv-executor-ysegev-node1.example.com  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3_brew2-virtualization-depr-7hltt_a4585a2c-ecd0-11e8-b487-fa163eeeea38_0(bfdfc5584571af9e321b847573746f5dc00612d0da3d2a135eca46c7d24c733c): Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: getPodNetworkAnnotation: failed to query the pod bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3 in out of cluster comm: Unauthorized

**Environment**:
- kubevirt-ansible version(use `git rev-parse HEAD`):
- KubeVirt version (use `virtctl version`):
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`):
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leongold** [comment]
So I take the error isn't just about dangling configuration files, but rather that multus is not actually deprovisioned?

Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: getPodNetworkAnnotation: failed to query the pod bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3 in out of cluster comm: Unauthorized

**Comment by SchSeba** [comment]
We need to run on all the nodes and remove the multus cni config file ```/etc/cni/net.d/00-multus.conf``` also remove the multus binary can be a nice to have on deprovision.

**Comment by phoracek** [comment]
@leongold this is what happens:

1) We deprovision RBAC. CNI config and binaries are still on the node
2) Kubernetes picks first config (still multus)
3) Multus binary tries to reach cluster
4) If fails because of RBAC does not allow it anymore

**Comment by leongold** [comment]
aha, I see, thanks for the clarification @phoracek, I'll look into this

**Comment by rthallisey** [comment]
Solution was outlined here: https://bugzilla.redhat.com/show_bug.cgi?id=1651693
