### ISSUE TITLE
kubevirt-ansible tests are running with extra namespace argument

### ISSUE THREAD

**Issue by adityaramteke** [kubevirt/kubevirt-ansible#489]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Expected error:
        <*errors.errorString | 0xc4202562e0>: {
            s: "command failed: cannot run command \"/usr/bin/oc create -f tests/manifests/vm_with_sidecar_hook.yml -n kubevirt-test-default -n kubevirt-test-default\": exit status 1",
        }
        command failed: cannot run command "/usr/bin/oc create -f tests/manifests/vm_with_sidecar_hook.yml -n kubevirt-test-default -n kubevirt-test-default": exit status 1
    not to have occurred

Not required to give `kubevirt-test-default` namespace as RunCommand function takes it by default.

**What you expected to happen**:
Tests should run with the single namespace argument.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
External commands are not confined to an explicit namespace, unless "-n"
argument is added.  Since the original version of the tests.RunCommand()
function did not care about namespaces, it was susceptible to produce
errors that are hard to debug, e.g., creating a VMI in the 'default'
namespace instead of 'kubevirt-test-default'.  The extended version of
the tests.RunCommand() function also automatically adds "-n" argument to
confine the command to tests.NamespaceTestDefault namespace.  If one
would like to run external command in different namespace, e.g.,
tests.NamespaceTestAlternative, I have introduced a new function for
this purpose:

  tests.RunCommandWithNS(namespace, command, args...)

If it is not recommendable to place "-n" as the last argument, e.g., in
case of the 'kubectl exec ... -- ...' command, it is possible to
knock-off the automatic "-n" inclusion by passing an empty string:

  tests.RunCommandWithNS("", command, args...)

**Comment by shiywang** [comment]
I personally suggest we change cli_exec.go to 

```
	if r.expectOut != "" {
		Eventually(func() bool {
			r.actualOut, _, err = ktests.RunCommandWithNS(r.nameSpace, r.cmd, cmd...)
			Expect(err).ToNot(HaveOccurred())
			return strings.Contains(r.actualOut, r.expectOut)
		}, timeout).Should(BeTrue(), fmt.Sprintf("Timed out waiting for %s to appear", r.resourceType))
	} else {
		r.actualOut, _, err = ktests.RunCommandWithNS(r.nameSpace, r.cmd, cmd...)
		Expect(err).ToNot(HaveOccurred())
	}
	return r.actualOut
}
```
