### ISSUE TITLE
Sidecar hook tests uses fc27 VMI

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#508]
fc27 is obsolete, thus we shouldn't use it in our tests.

**Comment by ILpinto** [comment]
@gbenhaim 
You can see that in the yaml we not point to specific version: 
registryDisk:
      image: kubevirt/fedora-cloud-registry-disk-demo:latest  
But it not only on this test all the tests are pointing to the same docker namespace and with label latest. 
See: kubevirt/tests/utils.go 
method: RegistryDiskFor
We don't need to change the tests we need to update the image on docker.io/kubevirt
I just don't know who is responsible for it.
