### ISSUE TITLE
Failed to deploy multus/skydive by playbooks/network.yml due to the 'deploy_ovs_plugin' is undefined

### ISSUE THREAD

**Issue by duyanyan** [kubevirt/kubevirt-ansible#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
$ ansible-playbook -i inventory -e apb_action=provision -e deploy_skydive=True playbooks/network.yml

PLAY [nodes masters] **********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
Wednesday 05 December 2018  09:39:41 +0000 (0:00:00.072)       0:00:00.072 ****
ok: [cnv-executor-yadu-node1.example.com]
ok: [cnv-executor-yadu-node2.example.com]
ok: [cnv-executor-yadu-master1.example.com]

TASK [make sure ovs is installed] *********************************************************************************************************************************************************************************
Wednesday 05 December 2018  09:39:42 +0000 (0:00:01.535)       0:00:01.608 ****
fatal: [cnv-executor-yadu-master1.example.com]: FAILED! => {}

MSG:

The conditional check 'network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"' failed. The error was: error while evaluating conditional (network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"): 'deploy_ovs_plugin' is undefined

The error appears to have been in '/home/cnv-qe-jenkins/kubevirt-ansible/playbooks/network.yml': line 9, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make sure ovs is installed
        ^ here

fatal: [cnv-executor-yadu-node1.example.com]: FAILED! => {}

MSG:

The conditional check 'network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"' failed. The error was: error while evaluating conditional (network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"): 'deploy_ovs_plugin' is undefined

The error appears to have been in '/home/cnv-qe-jenkins/kubevirt-ansible/playbooks/network.yml': line 9, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make sure ovs is installed
        ^ here

fatal: [cnv-executor-yadu-node2.example.com]: FAILED! => {}

MSG:

The conditional check 'network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"' failed. The error was: error while evaluating conditional (network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"): 'deploy_ovs_plugin' is undefined

The error appears to have been in '/home/cnv-qe-jenkins/kubevirt-ansible/playbooks/network.yml': line 9, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make sure ovs is installed
        ^ here

    to retry, use: --limit @/home/cnv-qe-jenkins/kubevirt-ansible/playbooks/network.retry

PLAY RECAP **************************************************************************************************************************

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubevirt-ansible version(use `git rev-parse HEAD`): 
- KubeVirt version (use `virtctl version`): 
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`): Openshift
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by duyanyan** [comment]
The cluster and platform var are not defined as well after solving the deploy_ovs_plugin. I think it is better to run some checking config script and then defined the vars at the beginning. 

The conditional check 'network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"' failed. The error was: error while evaluating conditional (network_role == 'network-multus' and deploy_ovs_plugin and cluster == "kubernetes"): 'cluster' is undefined

The error appears to have been in '/tmp/kubevirt-ansible/playbooks/network.yml': line 10, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make sure ovs is installed
        ^ here


The conditional check 'platform=="openshift"' failed. The error was: error while evaluating conditional (platform=="openshift"): 'platform' is undefined

The error appears to have been in '/tmp/kubevirt-ansible/roles/network-multus/tasks/provision.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: oc Command
  ^ here

**Comment by duyanyan** [comment]
@leongold Cool! Your PR works and added a comment on your PR.

**Comment by leongold** [comment]
@duyanyan Thank you, made the changes as you specified
