### ISSUE TITLE
Add featuregates to support 0.12 functionality

### ISSUE THREAD

**Issue by nellyc** [kubevirt/kubevirt-ansible#532]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
/kind enhancement

**What happened**:
We need to add some featuregates
live migration, cpu manager

**What you expected to happen**:
feature gates enabled

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kubevirt-ansible version(use `git rev-parse HEAD`):
should be on master and on a new 0.12 tag
- KubeVirt version (use `virtctl version`):
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`):
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by myakove** [comment]
added in https://github.com/kubevirt/kubevirt-ansible/pull/533

**Comment by kbidarkar** [comment]
@nellyc, the needed changes are added from 0.12, so can we close this now?
