### ISSUE TITLE
We need to run with OpenShift 3.9 instead of 3.7

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#54]
There are KubeVirt features which doesn't work on 3.7 and we need to give option to people to deploy KubeVirt on the top of 3.9.

Be aware that `byo/config.yml` playbook doesn't exists 3.9: https://github.com/openshift/openshift-ansible/issues/6503

**Comment by lukas-bednar** [comment]
It is being worked as a part of #61

**Comment by cynepco3hahue** [comment]
@lukas-bednar Just be aware that openshift-ansible under master branch again has an issue with RPM check - https://github.com/openshift/openshift-ansible/issues/6756

**Comment by gbenhaim** [comment]
done https://github.com/kubevirt/kubevirt-ansible/pull/61
