### ISSUE TITLE
"Version" on CDI main.yaml

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#589]
Hi,

From https://github.com/kubevirt/kubevirt-ansible/blob/master/roles/cdi/defaults/main.yml

cdi_release_tag: "v1.5.1"
version: "1.4.0"

I was wondering, where the "version" is used? Is it kubevirt version?

Thanks.

**Comment by kbidarkar** [comment]
@qwang1, git blame shows, brought in by me and I did not touch that part, maybe got in while resolving git conflicts. Me looking.

**Comment by kbidarkar** [comment]
So, I thought it was me, but realized  I was just updating kubevirt versions. :)

This will be a question for @tiraboschi, he can help about it I think.
