### ISSUE TITLE
Do we need flow mode=dev ?

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#62]
I think we don't need to maintain flow which deploys KubeVirt from sources.

**Comment by fabiand** [comment]
I tend to agree.

If dev setup is needed, then a developer can build it from the sources.

Only releases must be covered by the ansible modules-

**Comment by lukas-bednar** [comment]
@fabiand ok we can remove this part from repository.

**Comment by gbenhaim** [comment]
+1

**Comment by karmab** [comment]
while developers should build from source, i think we should be able to deploy latest whenever from some "artifacts" ( apb, playbook or templates)

**Comment by fabiand** [comment]
So, I think we can say that the dev mode is manual only and does not neede to be covered in the playbook.

**Comment by lukas-bednar** [comment]
It is time to finalize the decision. We want to pick from these two statements:
* Keep and stabilize `mode=dev` flow
* Remove `mode=dev` flow

From comments above I understand that we want to "remove `mode=dev` flow".
I will remove all relevant parts.

**Comment by fabiand** [comment]
+1 Please remove it.

**Comment by lukas-bednar** [comment]
removed here #70
