### ISSUE TITLE
Update README to reflect latest supported platform version

### ISSUE THREAD

**Issue by eedri** [kubevirt/kubevirt-ansible#65]
Currently README states that supported platforms are:
CentOS Linux release 7.3.1611 (Core), OpenShift 3.7 and Ansible 2.3.1

We should probably create a new testing matrix table and include the currently supported versions
and the ones which are in progress.

e.g:

Supported | In Development
------------ | ------------------------
CentOS 7.4 | N/A
OpenShift 3.7 | OpenShift 3.9
Ansible 2.3.1 | Ansible 2.4.2

**Comment by lukas-bednar** [comment]
I can add such table in this pull request #60 .
But we moved forward with Ansible, now we run 2.4.2 for OpenShift 3.7 as well.

**Comment by eedri** [comment]
duplicate #60
