### ISSUE TITLE
CI tests should ignore documentation changes

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt-ansible#76]
CI should ignore commits containing [ci skip] and [skip ci] in their title or description. [ci skip] and [skip ci] can be used for documentation and minor changes which don't require CI check.

**Comment by eedri** [comment]
We should be very careful with such kind of tags, its a big opening for allowing PRs to get merged w/o CI tests. 

A better solution is for the CI system to detect its a text change and not run validation on it.

**Comment by gbenhaim** [comment]
I agree with @eedri. CI should be triggered for each PR.
In the automation scripts, we can implement a logic which skips the cluster deployment and tests if the code didn't change.

**Comment by alexxa** [comment]
https://github.com/kubevirt/kubevirt-ansible/pull/74#issuecomment-366701197

**Comment by eedri** [comment]
+1 for the issue, we should update the automation/check-patch.sh script to detect documentation.
Another option is to add another sub-stage for testing documentation ( like spell-checker )
