### ISSUE TITLE
Add documentation about standard-ci which is running behind each pr

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt-ansible#77]
* add information about standard-ci
* describe what is being executed

**Comment by eedri** [comment]
A lot of the docs can be found here: http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Build_and_test_standards/index.html

Specifically for GitHub here:
http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Using_STDCI_with_GitHub/index.html

We're also working in extending the docs on the new DSL soon. 
I agree we should add a CI.md doc to add links to these and contain info specific for KubeVirt Ansible

**Comment by lukas-bednar** [comment]
@eedri thanks for your input, I will include these links there.

> I agree we should add a CI.md doc to add links to these and contain info specific for KubeVirt Ansible

My plan is add `automation/README.md` with that info, and link this file from main `README.md` located in root of repository.
