### ISSUE TITLE
The "byo" directory isn't in openshift-ansible any longer. 

### ISSUE THREAD

**Issue by dyasny** [kubevirt/kubevirt-ansible#78]
https://github.com/kubevirt/kubevirt-ansible/blob/1274f08e63562164243833a6f1cfcc3916fead49/deploy-openshift.yml#L27

The playbook is now at playbooks/deploy_cluster.yml

**Comment by lukas-bednar** [comment]
Thanks for report, this is being addressed in #61

**Comment by lukas-bednar** [comment]
@dyasny the PR #61 was merged, it addressed this issue, can I close ?

**Comment by dyasny** [comment]
@lukas-bednar Please do :)

**Comment by lukas-bednar** [comment]
fixed via #61
