### ISSUE TITLE
Stop using hosts:all 

### ISSUE THREAD

**Issue by dyasny** [kubevirt/kubevirt-ansible#86]
In several locations some plays are run against hosts: all. This presents a problem when more than just the k8s/openshift cluster is managed in the inventory, e.g. when there are ceph or gluster nodes in place or when the setup is being run on a local hypervisor and the hypervisor is in the inventory as "hypervisor" and should not be altered like the k8s cluster nodes. 

https://github.com/kubevirt/kubevirt-ansible/blob/6f32ae31095b2342f32c3f6ab64cc03a6db305a0/deploy-kubernetes.yml#L2

https://github.com/kubevirt/kubevirt-ansible/blob/0e5ae43551e1b50e569a303e9ca53e02b5705988/install-kubevirt-release.yml#L1

https://github.com/kubevirt/kubevirt-ansible/blob/2ef2c8ba752af53f9f43601dc76174649076d96e/deploy-openshift.yml#L2

https://github.com/kubevirt/kubevirt-ansible/blob/b9f4b40d2d8751e2bf82ee667fb20c71a8ea2d0a/deploy-with-lago.yml#L39

**Comment by nellyc** [comment]
@dcritch please check your PR, update and merge :)

**Comment by shiywang** [comment]
@nellyc guess we can close this one
