### ISSUE TITLE
We have 2 variables dirs in the root of the repo

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt-ansible#96]
We have:

- vars
- variables.

I think that we should have only one of them, and I prefer the name `vars` since it's part of the ansible jargon.

In addition, we have `all.yaml` and `global_vars.yml`, do you think that we should keep both of them?
I think that `global_vras.yml` should contain miscellaneous vars, while `all.yaml` should contain vars that are related to Kubevirt's deployment, and should be renamed to a meaningful name.

**Comment by gbenhaim** [comment]
@rthallisey @lukas-bednar @alexxa thoughts?

**Comment by dyasny** [comment]
"variables" is something that has no place in an ansible playbook structure. Usually it's defaults to contain the default definitions and vars for either random additional variable or as a placeholder dir for replacements for the defaults.

**Comment by alexxa** [comment]
- Keep vars directory, not variables.
- +1 on renaming. Since things which are in `all.yaml` belong to KubeVirt's deployment only.
- There is inconsistency in naming other files containing vars. E.g. see
     * playbooks/cluster/kubernetes/vars/default_vars.yml
     * kubevirt-ansible/playbooks/cluster/openshift/vars/

     I think it can be simply: playbooks/cluster/kubernetes/vars/defaults.yml

- roles/kubevirt/defaults/main.yml and similar can be changed to roles/kubevirt/defaults.yml. See
http://docs.ansible.com/ansible/latest/include_vars_module.html#examples
- Let's have consistency and use `yml` or `yaml`, not both? Most of YAML files in this git repo are `yml`. Just few are `yaml`.

**Comment by gbenhaim** [comment]
https://github.com/kubevirt/kubevirt-ansible/pull/98

**Comment by alexxa** [comment]
@gbenhaim don't close this issue yet, please. I want to fix other things I mentioned in my previous comment.

**Comment by rthallisey** [comment]
Copying my comment from #98:

> IMO we should keep a top level variable file for folks to override variables. This will come in handy when we only want to expose a subset of variables. For example when we add components, we will want to expose a variable like enable_cinder: true at the top level. But, at a lower level, something like dev_template_resources:, which is not likely to change, we leave in defaults/main.yml
>
Changing the name from variables to vars is fine with me.

Agreed @alexxa, we should be consistent with our extensions and naming.

**Comment by nellyc** [comment]
@rthallisey any updates on this one?
